# codecov config
coverage:
  status:
    project:
      default:
        threshold: 1%
    patch: false
ignore:
  - "**/error*.rs"        # ignore all error.rs files
comment:                  # this is a top-level key
  layout: "diff"
