// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: hello/v1/hello.proto
// Protobuf C++ Version: 5.28.3

#include "hello/v1/hello.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace rsketch {
namespace hello {
namespace v1 {
}  // namespace v1
}  // namespace hello
}  // namespace rsketch
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_hello_2fv1_2fhello_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_hello_2fv1_2fhello_2eproto = nullptr;
const ::uint32_t TableStruct_hello_2fv1_2fhello_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* schemas = nullptr;
static constexpr ::_pb::Message* const* file_default_instances = nullptr;
const char descriptor_table_protodef_hello_2fv1_2fhello_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\024hello/v1/hello.proto\022\020rsketch.hello.v1"
    "\032\033google/protobuf/empty.proto2@\n\005Hello\0227"
    "\n\005Hello\022\026.google.protobuf.Empty\032\026.google"
    ".protobuf.EmptyB\245\001\n\030com.rsketch.api.hell"
    "o.v1B\nHelloProtoZ0github.com/crrow/rsket"
    "ch/gen/go/hello/v1;helloPB\242\002\003RHX\312\002\020Rsket"
    "ch\\Hello\\V1\342\002\034Rsketch\\Hello\\V1\\GPBMetada"
    "ta\352\002\022Rsketch::Hello::V1b\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_hello_2fv1_2fhello_2eproto_deps[1] =
    {
        &::descriptor_table_google_2fprotobuf_2fempty_2eproto,
};
static ::absl::once_flag descriptor_table_hello_2fv1_2fhello_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_hello_2fv1_2fhello_2eproto = {
    false,
    false,
    311,
    descriptor_table_protodef_hello_2fv1_2fhello_2eproto,
    "hello/v1/hello.proto",
    &descriptor_table_hello_2fv1_2fhello_2eproto_once,
    descriptor_table_hello_2fv1_2fhello_2eproto_deps,
    1,
    0,
    schemas,
    file_default_instances,
    TableStruct_hello_2fv1_2fhello_2eproto::offsets,
    file_level_enum_descriptors_hello_2fv1_2fhello_2eproto,
    file_level_service_descriptors_hello_2fv1_2fhello_2eproto,
};
namespace rsketch {
namespace hello {
namespace v1 {
// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace hello
}  // namespace rsketch
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_hello_2fv1_2fhello_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
