# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: hello/v1/hello.proto
# Protobuf Python Version: 6.32.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    0,
    '',
    'hello/v1/hello.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14hello/v1/hello.proto\x12\x08hello.v1\"\"\n\x0cHelloRequest\x12\x12\n\x04name\x18\x01 \x01(\tR\x04name\")\n\rHelloResponse\x12\x18\n\x07message\x18\x01 \x01(\tR\x07message2H\n\x0cHelloService\x12\x38\n\x05Hello\x12\x16.hello.v1.HelloRequest\x1a\x17.hello.v1.HelloResponseB\x8c\x01\n\x18\x63om.rsketch.api.hello.v1B\nHelloProtoZ0github.com/crrow/rsketch/gen/go/hello/v1;hellopb\xa2\x02\x03HXX\xca\x02\x08Hello\\V1\xe2\x02\x14Hello\\V1\\GPBMetadata\xea\x02\tHello::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hello.v1.hello_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\030com.rsketch.api.hello.v1B\nHelloProtoZ0github.com/crrow/rsketch/gen/go/hello/v1;hellopb\242\002\003HXX\312\002\010Hello\\V1\342\002\024Hello\\V1\\GPBMetadata\352\002\tHello::V1'
  _globals['_HELLOREQUEST']._serialized_start=34
  _globals['_HELLOREQUEST']._serialized_end=68
  _globals['_HELLORESPONSE']._serialized_start=70
  _globals['_HELLORESPONSE']._serialized_end=111
  _globals['_HELLOSERVICE']._serialized_start=113
  _globals['_HELLOSERVICE']._serialized_end=185
# @@protoc_insertion_point(module_scope)
