# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: hello/v1/hello.proto
# Protobuf Python Version: 6.32.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    0,
    '',
    'hello/v1/hello.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14hello/v1/hello.proto\x12\x10rsketch.hello.v1\x1a\x1bgoogle/protobuf/empty.proto2@\n\x05Hello\x12\x37\n\x05Hello\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.EmptyB\xa5\x01\n\x18\x63om.rsketch.api.hello.v1B\nHelloProtoZ0github.com/crrow/rsketch/gen/go/hello/v1;helloPB\xa2\x02\x03RHX\xca\x02\x10Rsketch\\Hello\\V1\xe2\x02\x1cRsketch\\Hello\\V1\\GPBMetadata\xea\x02\x12Rsketch::Hello::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hello.v1.hello_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\030com.rsketch.api.hello.v1B\nHelloProtoZ0github.com/crrow/rsketch/gen/go/hello/v1;helloPB\242\002\003RHX\312\002\020Rsketch\\Hello\\V1\342\002\034Rsketch\\Hello\\V1\\GPBMetadata\352\002\022Rsketch::Hello::V1'
  _globals['_HELLO']._serialized_start=71
  _globals['_HELLO']._serialized_end=135
# @@protoc_insertion_point(module_scope)
