name: Release PR

on:
  workflow_call:

permissions:
  contents: write
  pull-requests: write

jobs:
  release-plz-pr:
    name: Create Release PR
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'crrow' && github.ref == 'refs/heads/main' }}
    concurrency:
      group: release-plz-${{ github.ref }}
      cancel-in-progress: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v6
        with:
          fetch-depth: false
          persist-credentials: false
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@67ef31d5b988238dd797d409d6f9574278e20537 # stable
        with:
          toolchain: stable
      - name: Install protoc
        uses: arduino/setup-protoc@c65c819552d16ad3c9b72d9dfd5ba5237b9c906b # v3.0.0
        with:
          version: '25.x'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Clean ignored files
        run: |
          rm -rf bin/
          git clean -fdX
      - name: Run release-plz
        uses: release-plz/action@e8792575c7f2366cf6ff3ccc33ead9ace5b691c7 # v0.5
        with:
          command: release-pr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
